[platformio]
default_envs = esp32cam

[common]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_flags =
    -DWIFI_SSID=${sysenv.WIFI_SSID}
    -DWIFI_PASS=${sysenv.WIFI_PASS}

; USB flash (via ESP32-CAM-MB programmer)
[env:esp32cam]
extends = common
upload_speed = 921600

; OTA flash (over WiFi — for sealed enclosure)
[env:esp32cam-ota]
extends = common
upload_protocol = espota
upload_port = ${sysenv.ESP32_IP}
